version: "3.8"

services:
  flutter-web:
    build:
      context: .
      dockerfile: Dockerfile
      # استخدام BuildKit لتحسين الأداء
      args:
        BUILDKIT_INLINE_CACHE: 1
    ports:
      - "80:80"
    container_name: syai-flutter-web
    restart: unless-stopped

    # إعدادات الصحة للتأكد من عمل التطبيق
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--quiet",
          "--tries=1",
          "--spider",
          "http://localhost:80",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

    # حدود الموارد لتحسين الأداء
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
