name: flutter_oauth_chat
description: SyAi - Revolutionary AI Assistant for Marketing Analytics and Campaign Management
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  dio: ^5.8.0+1
  web_socket_channel: ^2.4.0
  get_storage: ^2.1.1
  universal_html: ^2.2.4
  url_strategy: ^0.3.0
  intl: ^0.19.0
  supabase_flutter: ^2.9.0
  positioned_scroll_observer: ^2.2.2
  flutter_dotenv: ^5.1.0
  flutter_web_auth_2: ^4.1.0
  image_picker: ^1.0.4
  fl_chart: ^0.68.0
  data_table_2: ^2.5.15
  csv: ^6.0.0
  pdf: ^3.10.8
  excel: ^4.0.6
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - .env
